/**
 * Status Enums for Vastra ERP
 */

const INVENTORY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  SOLD: 'SOLD',
  RESERVED: 'RESERVED',
  ALTERED: 'ALTERED',
  RETURNED: 'RETURNED',
  GOODS_RETURNED: 'GOODS_RETURNED',
  IN_TRANSIT: 'IN_TRANSIT',
  DAMAGED: 'DAMAGED'
};

const LIFECYCLE_EVENT = {
  PURCHASE: 'PURCHASE',
  SALE: 'SALE',
  ALTERATION: 'ALTERATION',
  RETURN: 'RETURN',
  EXCHANGE: 'EXCHANGE',
  GOODS_RETURN: 'GOODS_RETURN',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT'
};

const BILL_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  RETURNED: 'RETURNED',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED',
  EXCHANGED: 'EXCHANGED',
  PARTIALLY_EXCHANGED: 'PARTIALLY_EXCHANGED'
};

const PAYMENT_MODE = {
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  DUE: 'DUE',
  ADVANCE: 'ADVANCE',
  GIFT_VOUCHER: 'GIFT_VOUCHER',
  CREDIT_NOTE: 'CREDIT_NOTE',
  POINTS: 'POINTS'
};

const LEDGER_TYPE = {
  ADVANCE: 'ADVANCE',
  DUE: 'DUE',
  LOYALTY: 'LOYALTY',
  PAYMENT: 'PAYMENT',
  REFUND: 'REFUND',
  ADJUSTMENT: 'ADJUSTMENT'
};

const ALTERATION_STATUS = {
  RECEIVED: 'Pending',
  PENDING: 'Pending',
  IN_CUTTING: 'In Cutting',
  IN_STITCHING: 'In Stitching',
  IN_PROGRESS: 'In Progress',
  IN_TRIAL: 'In Trial',
  READY_FOR_TRIAL: 'Ready for Trial',
  RE_ALTERATION: 'Re-Alteration',
  QUALITY_CHECK: 'Quality Check',
  READY: 'Ready',
  READY_FOR_DELIVERY: 'Ready for Delivery',
  DELIVERED: 'Delivered',
  CANCELLED: 'Cancelled'
};

const TENANT_STATUS = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  PENDING: 'PENDING'
};

module.exports = {
  INVENTORY_STATUS,
  LIFECYCLE_EVENT,
  BILL_STATUS,
  PAYMENT_MODE,
  LEDGER_TYPE,
  ALTERATION_STATUS,
  TENANT_STATUS
};
